# Generated by Django 6.0.5 on 2026-06-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('module_id', models.CharField(blank=True, choices=[('linear', 'Linear Functions'), ('quadratic', 'Quadratics'), ('trig', 'Sine Waves'), ('derivative', 'Derivatives'), ('integral', 'Integrals'), ('geometry', 'Geometry'), ('transform', 'Linear Transforms')], max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('body_md', models.TextField(help_text='Markdown body')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
