# Generated by Django 6.0.5 on 2026-06-07 15:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='whiteboarddrawing',
            name='module_slug',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='whiteboarddrawing',
            name='strokes_json',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='whiteboarddrawing',
            index=models.Index(fields=['user', 'module_slug', '-updated_at'], name='whiteboard__user_id_e21c09_idx'),
        ),
    ]
